--常量定义

--标题菜单常量
RFZTITLE_NEWGAME=1;
RFZTITLE_LOADGAME=2;
RFZTITLE_CG=3;
RFZTITLE_CGMEMORY=4;
RFZTITLE_EXIT=5;
--

--游戏菜单常量
RFZGAMEMENU_TITLE=1;
RFZGAMEMENU_SAVEGAME=2;
RFZGAMEMENU_LOADGAME=3;
RFZGAMEMENU_LOG=4;
RFZGAMEMENU_EXIT=5;
--